### ISSUE TITLE
MIDI file does not load..?

### ISSUE THREAD

**Issue by gregsadetsky** [feross/bitmidi.com#105]
Hello,

Thanks for the great site! I wanted to report a problem that I just stumbled upon. To repro:
- Go to https://bitmidi.com/georgia-on-my-mind-mid
- Click any of the Related MIDI files, such as "Georgia-On-My-Mind-1.mid" which updates the URL to https://bitmidi.com/georgia-on-my-mind-1-mid

The page shows "Loading georgia-on-my-mind-1-mid…" and is stuck there.

In the dev console, I'm seeing 400 errors from api.purpleads.io (even in incognito mode, with ad blockers disabled), not sure if that might be related.

Cheers

**Comment by nicobrinkkemper** [comment]
I am having the exact same issues. It's there for all browsers. The site itself is very broken and has been for some time now.
Going back to the homepage does allow some functionality, but any navigation after that is broken. For example, clicking other midis or typing in a new search query will result in a broken website.

**Comment by feross** [comment]
Thanks for the report. This is a known issue with the search function. I'll look into getting it fixed as soon as I can.
