### ISSUE TITLE
Search Query issues (SQL Error on unescaped queries & false results)

### ISSUE THREAD

**Issue by flxwu** [feross/bitmidi.com#32]
We have multiple issues here:

### 1. Special characters result in following error:
```
Error: select * from `midis` where MATCH(name) AGAINST('!--' IN BOOLEAN MODE) limit 10 - ER_PARSE_ERROR: syntax error, unexpected '-'
    at sendRequest (api.mjs:40)
```
![image](https://user-images.githubusercontent.com/16862997/44140569-b9cf3c44-a07a-11e8-9cf8-551540a0b64b.png)

### 2. Whole-word queries including a hyphen "-" return all titles except the one we search for:

![image](https://user-images.githubusercontent.com/16862997/44140636-f233370c-a07a-11e8-8f2e-0da5510d2eb5.png)

**Comment by feross** [comment]
This is already fixed because I changed the search to use natural language mode instead of boolean mode. See here: https://github.com/feross/bitmidi.com/blob/master/src/api/midi.mjs#L92
