### ISSUE TITLE
Autoplay support

### ISSUE THREAD

**Issue by samuelmaddock** [feross/bitmidi.com#58]
It'd be nice to have autoplay support using a search parameter in the URL such as `?autoplay`.
e.g. https://bitmidi.com/evangelion-cruel-angels-thesis-mid?autoplay=true

Context: I'm building an application for syncing media on the web—[Metastream](https://github.com/samuelmaddock/metastream)—and it'd be awesome to be able to support bitmidi.

**Comment by feross** [comment]
We support this now, but only on the `/embed` URLs which are intended to be embedded: https://bitmidi.com/embed/evangelion-cruel-angels-thesis-mid?autoplay=1
