### ISSUE TITLE
BitMidi is down, isn't secure

### ISSUE THREAD

**Issue by InfinityUniverse496** [feross/bitmidi.com#97]
When I try to open the website, it says your connection isn't secure.

**Comment by feross** [comment]
What browser and OS are you using?

**Comment by InfinityUniverse496** [comment]
Chrome, and this screenshot came up:
![2020-05-07 (1)](https://user-images.githubusercontent.com/64976377/81332496-2b470400-9071-11ea-9952-81ca9d9a0311.png)

**Comment by InfinityUniverse496** [comment]
Chrome, and this screenshot came up:
![2020-05-07 (1)](https://user-images.githubusercontent.com/64976377/81332539-3d28a700-9071-11ea-8481-bbdb5cc54fd8.png)

**Comment by InfinityUniverse496** [comment]
Please reply

**Comment by PatNeedham** [comment]
@InfinityUniverse496 what version of Chrome are you using? On chrome for Android 81.0.4044.138 for me it loads and renders just fine. Try in incognito tab maybe?

**Comment by InfinityUniverse496** [comment]
It looks like the internet isn't going to load the site

**Comment by InfinityUniverse496** [comment]
The error is NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by feross** [comment]
@InfinityUniverse496 Can you visit `chrome://version/` and copy and paste the version information here?

**Comment by InfinityUniverse496** [comment]
The website works now! ;)
